// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BuyCard: typeof import('./src/components/BuyCard.vue')['default']
    BuyDetail: typeof import('./src/components/BuyDetail.vue')['default']
    BuyNotice: typeof import('./src/components/BuyNotice.vue')['default']
    BuyPackage: typeof import('./src/components/BuyPackage.vue')['default']
    CdnImg: typeof import('./src/components/CdnImg.vue')['default']
    CustomHeader: typeof import('./src/components/CustomHeader.vue')['default']
    CustomTabBar: typeof import('./src/components/CustomTabBar.vue')['default']
    GoodsBox: typeof import('./src/components/GoodsBox.vue')['default']
    GoodsItem: typeof import('./src/components/GoodsItem.vue')['default']
    InputBox: typeof import('./src/components/InputBox.vue')['default']
    ListStatus: typeof import('./src/components/ListStatus.vue')['default']
    NavAndPhone: typeof import('./src/components/NavAndPhone.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutCheckbox: typeof import('@nutui/nutui-taro')['Checkbox']
    NutCol: typeof import('@nutui/nutui-taro')['Col']
    NutCountdown: typeof import('@nutui/nutui-taro')['Countdown']
    NutDialog: typeof import('@nutui/nutui-taro')['Dialog']
    NutDivider: typeof import('@nutui/nutui-taro')['Divider']
    NutEllipsis: typeof import('@nutui/nutui-taro')['Ellipsis']
    NutInputNumber: typeof import('@nutui/nutui-taro')['InputNumber']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutRadio: typeof import('@nutui/nutui-taro')['Radio']
    NutRadioGroup: typeof import('@nutui/nutui-taro')['RadioGroup']
    NutRow: typeof import('@nutui/nutui-taro')['Row']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
    NutTabPane: typeof import('@nutui/nutui-taro')['TabPane']
    NutTabs: typeof import('@nutui/nutui-taro')['Tabs']
    NutTag: typeof import('@nutui/nutui-taro')['Tag']
    Pay: typeof import('./src/components/Pay.vue')['default']
    SafeAreaView: typeof import('./src/components/SafeAreaView.vue')['default']
    TextareaBox: typeof import('./src/components/TextareaBox.vue')['default']
  }
}
