// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CdnImg: typeof import('./src/components/CdnImg.vue')['default']
    CustomHeader: typeof import('./src/components/CustomHeader.vue')['default']
    CustomTabBar: typeof import('./src/components/CustomTabBar.vue')['default']
    InputBox: typeof import('./src/components/InputBox.vue')['default']
    ListStatus: typeof import('./src/components/ListStatus.vue')['default']
    NavAndPhone: typeof import('./src/components/NavAndPhone.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCheckbox: typeof import('@nutui/nutui-taro')['Checkbox']
    NutCol: typeof import('@nutui/nutui-taro')['Col']
    NutRow: typeof import('@nutui/nutui-taro')['Row']
    SafeAreaView: typeof import('./src/components/SafeAreaView.vue')['default']
    TextareaBox: typeof import('./src/components/TextareaBox.vue')['default']
  }
}
