export default{
  '/static/tabBar/home.png': require('/static/tabBar/home.png'),
  '/static/tabBar/home_h.png': require('/static/tabBar/home_h.png'),
  '/static/tabBar/me.png': require('/static/tabBar/me.png'),
  '/static/tabBar/me_h.png': require('/static/tabBar/me_h.png'),
  '/static/img/me/default.png': require('/static/img/me/default.png'),
  '/static/img/me/bg1.png': require('/static/img/me/bg1.png'),
  '/static/img/me/unpaid.png': require('/static/img/me/unpaid.png'),
  '/static/img/me/nouse.png': require('/static/img/me/nouse.png'),
  '/static/img/me/completed.png': require('/static/img/me/completed.png'),
  '/static/img/me/refunded.png': require('/static/img/me/refunded.png'),
  '/static/img/me/cs.png': require('/static/img/me/cs.png'),
  '/static/img/me/credential.png': require('/static/img/me/credential.png'),
  '/static/img/home/hot-header.png': require('/static/img/home/hot-header.png'),
  '/static/img/home/hot-title.png': require('/static/img/home/hot-title.png'),
  '/static/img/detail/attention.png': require('/static/img/detail/attention.png'),
  '/static/img/detail/home.png': require('/static/img/detail/home.png'),
  '/static/img/detail/mine.png': require('/static/img/detail/mine.png'),
  '/static/img/detail/share.png': require('/static/img/detail/share.png'),
  '/static/img/icon/aptitude.png': require('/static/img/icon/aptitude.png'),
  '/static/img/copy.png': require('/static/img/copy.png'),

}
